services:
  comunica:
    build:
      context: ./comunica
      network: host
    command: --freshWorker --invalidateCache --httpRetryCount 10 --context /tmp/context.json --port 4000 --timeout 600 --logLevel info
    network_mode: host
    volumes:
      - ./comunica/config.json:/tmp/config.json:ro
      # - ./comunica/context.json:/tmp/context.json:ro
      - ./comunica/context-alt.json:/tmp/context.json:ro
  solidserver:
    build:
      context: ./solidserver
      network: host
    command: --config /tmp/config.json --rootFilePath /data --port 3000 --baseUrl http://127.0.0.1:3000/
    network_mode: host
    volumes:
      - ./solidserver/config.json:/tmp/config.json:ro
      - ./solidserver/nbn-chist-era-annex-1-chemicals.ttl:/data/test/nbn-chist-era-annex-1-chemicals.ttl:ro
      - ./solidserver/nbn-chist-era-annex-1-chemicals-alt.ttl:/data/test/nbn-chist-era-annex-1-chemicals-alt.ttl:ro
